version: "2"

services:
    mysql:
        image: mariadb:10.0
        networks:
            stack_net:
                ipv4_address: 172.55.0.2
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        environment:
            MYSQL_ROOT_PASSWORD: drupal
        #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
        volumes:
            - ./docker-runtime/mysql/lib:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            stack_net:
                ipv4_address: 172.55.0.3
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PHP_UPLOAD_MAX_FILESIZE: 1G
            PHP_MAX_INPUT_VARS: 1G
        ports:
            - "8001:80"
    
    php-fpm:
        links:
            - mysql
        image: lordius/alpine-php_fpm
        networks:
            stack_net:
                ipv4_address: 172.55.0.4
        depends_on:
            - mysql
            - mailhog
        environment:
            CRONTAB_ENABLED: 0
            PHP_FPM_PORT: 7000
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -i -t
            PHP_SENDMAIL_HOST: mailhog
            PHP_SENDMAIL_PORT: 1025
            PHP_XDEBUG_ENABLED: 1
            PHP_XDEBUG_PORT: 8010
            PHP_MAX_EXECUTION_TIME: 250
            PHP_UPLOAD_MAX_FILESIZE: 1024M
            PHP_POST_MAX_SIZE: 756M
            PHP_ALLOW_URL_FOPEN: "On"
            PHP_ALWAYS_POPULATE_RAW_POST_DATA: -1
            PHP_MEMORY_LIMIT: 1024M
        volumes:
            - ./htdocs:/var/www/localhost/htdocs
            - ./crontasks.txt:/home/crontasks.txt
        extra_hosts:
            - "docker.lamp:172.53.0.6" 
        
    apache2_mpm:
        links:
            - php-fpm   
            - mysql
        depends_on:
            - mysql 
            - php-fpm
        image: lordius/alpine-apache
        networks:
            stack_net:
                ipv4_address: 172.55.0.5
        environment:
            PROXY_PASS: fcgi://php-fpm:7000/var/www/localhost/htdocs
            APACHE_LISTEN_PORT: 80
        ports:
            - "8004:80"
        volumes_from:
            - php-fpm   
            
    nginx:
        links:
            - apache2_mpm   
        depends_on:
            - apache2_mpm
        image: lordius/alpine-nginx
        networks:
            stack_net:
                ipv4_address: 172.55.0.6
        environment:
            KEEPALIVE_TIMEOUT: 3000
            LISTEN_PORT: 80
            SERVER_ROOT: /var/www/localhost/htdocs
            SERVER_NAME: localhost
            CLIENT_MAX_BODY_SIZE: 32m
            PROXY_CONNECT_TIMEOUT: 3000
            PROXY_SEND_TIMEOUT: 3000
            PROXY_READ_TIMEOUT: 3000
            SEND_TIMEOUT: 3000
            PROXY_PASS: http://apache2_mpm:80
        ports:
            - "8005:80"
        volumes_from:
            - php-fpm

    mailhog:
        image: lordius/alpine-mailhog
        networks:
            stack_net:
                ipv4_address: 172.55.0.7
        ports:
            - "8006:8025"

    ngrok:
        image: lordius/alpine-ngrok
        networks:
            stack_net:
                ipv4_address: 172.55.0.8
        ports:
            - "4040:4040"
        environment:
            ARGS: http 172.53.0.6:80
            
networks:
  stack_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.55.0.0/16
         gateway: 172.55.0.1
